"""empty message

Revision ID: 23caace903d8
Revises: 0d32342ac5c6
Create Date: 2020-08-16 08:49:22.632243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23caace903d8'
down_revision = '0d32342ac5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activity')
    # ### end Alembic commands ###
